spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${pg.hostname}/${pg.db_name}?stringtype=unspecified
    username: ${pg.username}
    password: ${pg.password}

pg:
##
## Safety catch! Avoid trashing a working database
##
## Uncomment to enable application
  hostname: localhost:5432
  username: postgres
  password: letmein
  db_name: debit_credit

customer:
  count: 1000000
  batch: 10000
