spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:${db.host}}/${DB_NAME:${db.name}}?stringtype=unspecified
    username: ${DB_USERNAME:${db.username}}
    password: ${DB_PASSWORD:${db.password}}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true

db:
  host: localhost:5432
  username: postgres
  password: letmein
  name: debit_credit
